import Link from "next/link";
import { notFound } from "next/navigation";
import { getDb } from "@/lib/db/client";
import { isUuid } from "@/lib/http";
import { getLeadDetail } from "@/lib/services/queries";
import type { Field } from "@/lib/domain/provenance";
import { ConfidenceMeter, LabelLegend, ProvenanceBadge } from "@/components/provenance";
import { DemoBadge, IcpBadge } from "@/components/status";
import { Badge } from "@/components/ui/badge";
import { EvidenceList, IcpFactors, OpportunitiesList, PainPointsList, ProfileRow, ScoreBreakdown, SignalsList, TechSignals, OperationalSignals } from "@/components/lead/sections";
import { fmtDate, pct } from "@/lib/utils";
import { PrintButton } from "./print-button";

export const dynamic = "force-dynamic";
export const metadata = { title: "Research report" };

export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!isUuid(id)) notFound();
  const d = await getLeadDetail(getDb(), id);
  if (!d) notFound();
  if (!d.report || !d.score || !d.qualification) {
    return (
      <div className="mx-auto max-w-2xl py-10 text-center">
        <h1 className="font-serif text-2xl">No research report yet</h1>
        <p className="mt-2 text-muted">
          {d.company.name} has not completed a research run.{" "}
          <Link href={`/leads/${id}`} className="text-accent underline">
            Open the lead
          </Link>{" "}
          to run research.
        </p>
      </div>
    );
  }
  const p = d.report.profile;
  const f = (k: keyof typeof p) => p[k] as Field<unknown> | undefined;

  return (
    <article className="mx-auto max-w-[880px]">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3 print:hidden">
        <p className="text-[13px] text-muted">
          <Link href="/leads" className="hover:underline">
            Leads
          </Link>{" "}
          /{" "}
          <Link href={`/leads/${id}`} className="hover:underline">
            {d.company.name}
          </Link>{" "}
          / Report
        </p>
        <PrintButton />
      </div>

      <header className="border-b border-line-strong pb-6">
        <p className="text-[13px] text-muted">Lead research report, generated {fmtDate(d.report.createdAt)}</p>
        <h1 className="mt-1 flex flex-wrap items-center gap-3 font-serif text-[32px] font-medium leading-tight tracking-tight">
          {d.company.name}
          {d.report.isDemo ? <DemoBadge /> : null}
        </h1>
        <div className="mt-4 grid gap-4 sm:grid-cols-4">
          <Metric label="ICP fit" value={`${d.qualification.fitScore}/100`} extra={<IcpBadge match={d.qualification.match} />} />
          <Metric label="Lead score" value={`${d.score.total}/100`} extra={<Badge tone="accent">Grade {d.score.grade}</Badge>} />
          <Metric label="Qualification" value={d.score.qualified ? "Qualified" : "Not qualified"} extra={d.score.needsReview ? <Badge tone="warn">Needs review</Badge> : null} />
          <Metric label="Data completeness" value={pct(d.report.dataCompleteness)} extra={<ConfidenceMeter value={d.report.dataCompleteness} showText={false} />} />
        </div>
        {d.report.isDemo ? (
          <p className="mt-4 rounded-md border border-prov-demo/30 bg-[#f3eefb] px-3 py-2 text-[13px]">
            Simulated demo research: every company fact below comes from a fictional fixture in the mock research provider. It is not real research.
          </p>
        ) : null}
        <div className="mt-4">
          <p className="mb-1.5 text-xs text-muted">Evidence labels used in this report</p>
          <LabelLegend />
        </div>
      </header>

      <Section title="Executive summary">
        <p className="font-serif text-[16px] leading-relaxed">{d.report.summary}</p>
        <p className="mt-2 text-xs text-muted">Generated by {d.report.summaryGeneratedBy} from the stored findings. Pain points and opportunities are hypotheses.</p>
      </Section>

      <Section title="Company overview">
        {f("description") ? (
          <Claim field={f("description")!}>{String(f("description")!.value)}</Claim>
        ) : (
          <p className="text-muted">Insufficient data to verify a company description.</p>
        )}
        <dl className="mt-3">
          <ProfileRow k="industry" field={f("industry")} />
          <ProfileRow k="target_customers" field={f("target_customers")} />
        </dl>
      </Section>

      <Section title="Business model">
        <dl>
          <ProfileRow k="business_model" field={f("business_model")} />
        </dl>
      </Section>

      <Section title="Products and services">
        <dl>
          <ProfileRow k="services" field={f("services")} />
          <ProfileRow k="products" field={f("products")} />
        </dl>
      </Section>

      <Section title="Company size">
        <dl>
          <ProfileRow k="size_range" field={f("size_range")} />
        </dl>
      </Section>

      <Section title="Geography">
        <dl>
          <ProfileRow k="country" field={f("country")} />
          <ProfileRow k="locations" field={f("locations")} />
        </dl>
      </Section>

      <Section title="Technology signals">
        <TechSignals profile={p} />
        <p className="mb-2 mt-4 text-[13px] font-medium">Operational signals</p>
        <OperationalSignals profile={p} />
      </Section>

      <Section title="Buying signals" flush>
        <SignalsList signals={d.signals} />
      </Section>

      <Section title="Potential pain points" flush>
        <PainPointsList pains={d.pains} />
      </Section>

      <Section title="AI automation opportunities" flush>
        <OpportunitiesList opps={d.opps} />
      </Section>

      <Section title="ICP analysis" flush>
        <IcpFactors q={d.qualification} />
      </Section>

      <Section title="Lead score">
        <p className="text-[15px]">
          <span className="tabular text-3xl font-semibold">{d.score.total}</span>
          <span className="text-muted">/100, grade {d.score.grade}. </span>
          {d.score.qualified ? "At or above the qualification threshold." : "Below the qualification threshold or needs review."}
        </p>
        {d.score.reviewReasons.length ? (
          <ul className="mt-2 list-disc pl-5 text-[13px] text-warn">
            {d.score.reviewReasons.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        ) : null}
      </Section>

      <Section title="Score breakdown" flush>
        <ScoreBreakdown score={d.score} />
      </Section>

      <Section title="Recommended outreach angle">
        <div className="flex items-start gap-2">
          <ProvenanceBadge label="inferred" />
          <p className="font-serif text-[16px] leading-relaxed">{d.report.recommendedAngle}</p>
        </div>
      </Section>

      <Section title="Sources" flush>
        <EvidenceList evidence={d.report.evidence} />
      </Section>
    </article>
  );
}

function Section({ title, children, flush }: { title: string; children: React.ReactNode; flush?: boolean }) {
  return (
    <section className="border-b border-line py-6 print:break-inside-avoid">
      <h2 className="mb-3 font-serif text-xl font-medium">{title}</h2>
      <div className={flush ? "-mx-4 overflow-hidden rounded-lg border border-line bg-surface sm:mx-0" : ""}>{children}</div>
    </section>
  );
}

function Metric({ label, value, extra }: { label: string; value: string; extra?: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs text-muted">{label}</p>
      <p className="tabular text-lg font-semibold">{value}</p>
      <div className="mt-1">{extra}</div>
    </div>
  );
}

function Claim({ field, children }: { field: Field<unknown>; children: React.ReactNode }) {
  return (
    <div>
      <p className="font-serif text-[16px] leading-relaxed">{children}</p>
      <span className="mt-1.5 flex flex-wrap items-center gap-2">
        <ProvenanceBadge label={field.provenance.label} provenance={field.provenance} />
        <ConfidenceMeter value={field.provenance.confidence} />
        <span className="text-xs text-muted">{field.provenance.source}</span>
      </span>
    </div>
  );
}
