import Link from "next/link";
import { CircleAlert } from "lucide-react";
import { getLandingPreview } from "@/lib/services/preview";
import type { Field } from "@/lib/domain/provenance";
import { buttonVariants } from "@/components/ui/button";
import { Logo } from "@/components/logo";
import { ConfidenceMeter, ProvenanceBadge } from "@/components/provenance";
import { IcpBadge } from "@/components/status";
import { Badge } from "@/components/ui/badge";
import { PIPELINE_STEPS } from "@/components/agent/pipeline";

export const dynamic = "force-dynamic";

export default async function Landing() {
  const { state, company } = await getLandingPreview();
  const p = state.profile!;
  const icp = state.icpResult!;
  const score = state.score!;
  const email = state.outreach?.drafts.find((d) => d.channel === "email");
  const signal = state.signals?.accepted[0];
  const pain = state.painPoints?.[0];
  const opp = state.opportunities?.[0];
  const claims = (["industry", "size_range", "country"] as const).map((k) => [k, p[k] as Field<unknown> | undefined] as const);

  return (
    <div className="bg-surface">
      <header className="border-b border-line">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-3">
          <Logo />
          <nav className="flex items-center gap-1 text-[13.5px]">
            <a href="#how" className="hidden rounded px-2.5 py-1.5 text-ink-2 hover:bg-paper sm:inline">
              How it works
            </a>
            <a href="#architecture" className="hidden rounded px-2.5 py-1.5 text-ink-2 hover:bg-paper sm:inline">
              Architecture
            </a>
            <Link href="/login" className="rounded px-2.5 py-1.5 text-ink-2 hover:bg-paper">
              Sign in
            </Link>
            <Link href="/demo" className={buttonVariants({ size: "sm" })}>
              Run the demo
            </Link>
          </nav>
        </div>
      </header>

      <section className="border-b border-line bg-paper">
        <div className="mx-auto grid max-w-6xl gap-10 px-5 py-14 lg:grid-cols-[1.05fr_1fr] lg:py-20">
          <div className="max-w-xl">
            <h1 className="font-serif text-[40px] font-medium leading-[1.08] tracking-tight text-ink sm:text-[52px]">Find the Right Leads. Know Why They Fit. Know What to Say.</h1>
            <p className="mt-5 text-[17px] leading-relaxed text-ink-2">
              AI-powered lead research and qualification with evidence-backed company analysis, transparent scoring, and personalized outreach.
            </p>
            <div className="mt-7 flex flex-wrap gap-3">
              <Link href="/demo" className={buttonVariants({ size: "lg" })}>
                Run the Example Logistics demo
              </Link>
              <Link href="/login" className={buttonVariants({ size: "lg", variant: "secondary" })}>
                Sign in
              </Link>
            </div>
            <p className="mt-5 max-w-md text-[13px] text-muted">
              A portfolio project for NovaFlow AI, a fictional automation agency. The demo researches fictional companies with a mock provider, and every result it produces is labelled Demo.
            </p>
          </div>

          <figure aria-label={`Lead dossier for ${company}, produced by the pipeline`} className="rounded-lg border border-line-strong bg-surface shadow-[0_1px_0_#dde2ea,0_12px_32px_-18px_rgba(23,32,51,0.35)]">
            <div className="flex items-center justify-between border-b border-line px-4 py-3">
              <div>
                <p className="font-serif text-lg font-medium">{company}</p>
                <p className="text-xs text-muted">Lead dossier, generated by the pipeline on this page load</p>
              </div>
              <Badge tone="demo">Demo data</Badge>
            </div>
            <div className="grid grid-cols-2 border-b border-line">
              <div className="border-r border-line px-4 py-3">
                <p className="text-xs text-muted">ICP fit</p>
                <p className="flex items-center gap-2">
                  <span className="tabular text-2xl font-semibold">{icp.fit_score}</span>
                  <IcpBadge match={icp.match} />
                </p>
              </div>
              <div className="px-4 py-3">
                <p className="text-xs text-muted">Lead score</p>
                <p className="flex items-center gap-2">
                  <span className="tabular text-2xl font-semibold">{score.total}</span>
                  <Badge tone="accent">Grade {score.grade}</Badge>
                </p>
              </div>
            </div>
            <dl className="divide-y divide-line text-[13px]">
              {claims.map(([k, f]) =>
                f ? (
                  <div key={k} className="flex items-center justify-between gap-3 px-4 py-2">
                    <dt className="w-24 shrink-0 text-muted">{k === "size_range" ? "Size" : k === "country" ? "Country" : "Industry"}</dt>
                    <dd className="flex-1 capitalize">{k === "size_range" ? `${(f.value as { label: string }).label} employees` : String(f.value)}</dd>
                    <ProvenanceBadge label={f.provenance.label} provenance={f.provenance} />
                  </div>
                ) : null,
              )}
              {signal ? (
                <div className="px-4 py-2">
                  <dt className="flex items-center justify-between gap-2">
                    <span className="text-muted">Buying signal</span>
                    <ConfidenceMeter value={signal.confidence} />
                  </dt>
                  <dd className="mt-0.5">{signal.signal}</dd>
                </div>
              ) : null}
              {pain ? (
                <div className="px-4 py-2">
                  <dt className="flex items-center justify-between gap-2">
                    <span className="text-muted">Pain point</span>
                    <ProvenanceBadge label="potential" />
                  </dt>
                  <dd className="mt-0.5">{pain.title}</dd>
                </div>
              ) : null}
              {email?.subject ? (
                <div className="px-4 py-2">
                  <dt className="text-muted">Draft email subject</dt>
                  <dd className="mt-0.5 font-medium">{email.subject}</dd>
                </div>
              ) : null}
            </dl>
            <figcaption className="flex items-center gap-2 border-t border-line bg-warn-soft px-4 py-2 text-xs font-semibold text-warn">
              <CircleAlert className="size-3.5" aria-hidden />
              AI GENERATED — REQUIRES HUMAN APPROVAL
            </figcaption>
          </figure>
        </div>
      </section>

      <main className="mx-auto max-w-6xl px-5">
        <Row id="problem" title="The problem">
          <ul className="space-y-3 text-[15px] leading-relaxed text-ink-2">
            <li>Sales teams spend hours opening websites and guessing whether a company is worth contacting.</li>
            <li>Lead scores from black-box tools cannot be explained to the rep who has to act on them.</li>
            <li>Outreach written from thin research is generic, or worse, confident about facts nobody checked.</li>
          </ul>
        </Row>

        <Row id="solution" title="The solution">
          <p className="text-[15px] leading-relaxed text-ink-2">
            An agent that researches each company, keeps a source and confidence for every fact, evaluates it against a configurable ideal customer profile with deterministic rules, and drafts outreach that a
            human approves before anything is sent. Every step is recorded and visible.
          </p>
        </Row>

        <Row id="how" title="How it works">
          <ol className="grid gap-x-6 gap-y-3 sm:grid-cols-3">
            {PIPELINE_STEPS.map((s, i) => (
              <li key={s.key} className="flex items-baseline gap-3 border-t border-line pt-3">
                <span className="tabular text-sm font-semibold text-accent">{i + 1}</span>
                <span className="text-[14.5px]">{s.label}</span>
              </li>
            ))}
          </ol>
          <p className="mt-4 text-[13px] text-muted">The planner chooses each next tool from those whose prerequisites are met; guardrails validate every choice and its arguments.</p>
        </Row>

        <Row id="research" title="Research with provenance">
          <p className="text-[15px] leading-relaxed text-ink-2">
            The research provider collects facts from the company website (fetched with SSRF protection, time and size limits, and robots.txt respected) and optional web search. Each fact is stored with its
            source, confidence and retrieval time, and labelled:
          </p>
          <div className="mt-3 flex flex-wrap gap-2">
            {(["verified", "source_backed", "estimated", "inferred", "demo", "potential"] as const).map((l) => (
              <ProvenanceBadge key={l} label={l} />
            ))}
          </div>
          <p className="mt-3 text-[13px] text-muted">When evidence is missing the report says so. The mock provider never invents facts for companies it does not know.</p>
        </Row>

        <Row id="icp" title="ICP matching">
          <p className="mb-3 text-[15px] leading-relaxed text-ink-2">A deterministic engine compares the profile with the ICP and explains every criterion. Output for {company}:</p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Criterion</th>
                <th className="text-right">Score</th>
                <th>Reason</th>
              </tr>
            </thead>
            <tbody>
              {icp.factors.map((f) => (
                <tr key={f.key}>
                  <td className="whitespace-nowrap font-medium">{f.factor}</td>
                  <td className="tabular whitespace-nowrap text-right">
                    {f.score}/{f.weight}
                  </td>
                  <td>{f.reason}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Row>

        <Row id="scoring" title="Transparent lead scoring">
          <p className="mb-3 text-[15px] leading-relaxed text-ink-2">Nine weighted factors, each with evidence and an explanation. Weights are editable by an admin.</p>
          <ul className="space-y-1.5">
            {score.factors.map((f) => (
              <li key={f.key} className="grid grid-cols-[150px_1fr_52px] items-center gap-3 text-[13px]">
                <span>{f.label}</span>
                <span className="h-1.5 overflow-hidden rounded-full bg-line" aria-hidden>
                  <span className="block h-full rounded-full bg-accent" style={{ width: `${f.ratio * 100}%` }} />
                </span>
                <span className="tabular text-right text-muted">
                  {f.score}/{f.weight}
                </span>
              </li>
            ))}
          </ul>
        </Row>

        <Row id="signals" title="Buying signals">
          <p className="text-[15px] leading-relaxed text-ink-2">
            Hiring, expansion, new services, support load and similar signals are kept only with evidence, a source and a confidence of at least 30%. Signals without evidence are rejected.
          </p>
          {signal ? (
            <p className="mt-3 rounded-md border border-line px-3 py-2 text-[13px]">
              <span className="font-medium">{signal.signal}</span> <span className="text-muted">({signal.strength})</span>
              <span className="mt-0.5 block text-muted">Evidence: {signal.evidence}</span>
            </p>
          ) : null}
        </Row>

        <Row id="pains" title="Pain points">
          <p className="text-[15px] leading-relaxed text-ink-2">Pain points are phrased as hypotheses and must cite observed evidence. Unhedged or unsupported statements are rejected by the validator.</p>
          {pain ? (
            <p className="mt-3 rounded-md border border-line px-3 py-2 text-[13px]">
              <ProvenanceBadge label="potential" /> <span className="ml-1 font-medium">{pain.title}</span>
              <span className="mt-0.5 block text-muted">{pain.description}</span>
            </p>
          ) : null}
        </Row>

        <Row id="opportunities" title="AI automation opportunities">
          <p className="text-[15px] leading-relaxed text-ink-2">Each pain point maps to a NovaFlow service with the problem, evidence, proposed solution, expected workflow and implementation complexity. No ROI figures are invented.</p>
          {opp ? (
            <div className="mt-3 rounded-md border border-line px-3 py-2 text-[13px]">
              <p className="font-medium">{opp.title}</p>
              <p className="text-muted">{opp.proposed_solution}</p>
            </div>
          ) : null}
        </Row>

        <Row id="outreach" title="Personalized outreach">
          <p className="mb-3 text-[15px] leading-relaxed text-ink-2">
            A cold email, a LinkedIn note and two follow-ups, written from the observations only. A validator checks names, personalisation, invented numbers, unknown technologies, unsupported claims, fake
            familiarity and tone, and returns PASS or NEEDS REVIEW with reasons.
          </p>
          {email ? (
            <div className="rounded-md border border-line bg-paper/60 p-3 text-[13px]">
              <p className="mb-2 border-b border-line pb-2">
                <span className="text-muted">Subject: </span>
                <span className="font-medium">{email.subject}</span>
              </p>
              <p className="whitespace-pre-wrap leading-relaxed">{email.body}</p>
              <p className="mt-2 text-xs text-muted">Quality check: {email.validation?.result === "PASS" ? "PASS" : "NEEDS REVIEW"}. Demo output from the mock AI provider.</p>
            </div>
          ) : null}
        </Row>

        <Row id="approval" title="Human approval">
          <p className="text-[15px] leading-relaxed text-ink-2">
            Drafts move from draft to review to approved, and a human records when a message was sent. The application never sends email, and the AI can never move a lead past Outreach drafted, let alone mark it
            Won.
          </p>
        </Row>

        <Row id="analytics" title="Analytics">
          <p className="text-[15px] leading-relaxed text-ink-2">
            Leads analysed, qualified, average score, ICP match rate, research success rate, drafts and approvals, plus distributions by score, stage, industry and opportunity, all computed from the database.
          </p>
        </Row>

        <Row id="architecture" title="Architecture">
          <div className="grid gap-2 text-[13px] sm:grid-cols-4">
            {[
              ["Next.js app", "Pages, route handlers, session auth, CSRF origin check"],
              ["Agent", "Planner + 11 tools with guardrails; mock or OpenAI-compatible model"],
              ["Engines", "Deterministic ICP, scoring, signal, pain-point and outreach validators"],
              ["PostgreSQL", "Drizzle schema, runs as a SKIP LOCKED work queue, full audit trail"],
            ].map(([t, d]) => (
              <div key={t} className="rounded-md border border-line px-3 py-2.5">
                <p className="font-medium">{t}</p>
                <p className="mt-0.5 text-muted">{d}</p>
              </div>
            ))}
          </div>
          <p className="mt-3 text-[13px] text-muted">Research and AI sit behind interfaces, so the mock providers and the real adapters share the same pipeline.</p>
        </Row>

        <Row id="stack" title="Tech stack">
          <dl className="grid grid-cols-[130px_1fr] gap-y-1.5 text-[14px]">
            <dt className="text-muted">Application</dt>
            <dd>Next.js App Router, React, TypeScript, Tailwind CSS</dd>
            <dt className="text-muted">Data</dt>
            <dd>PostgreSQL, Drizzle ORM, Zod</dd>
            <dt className="text-muted">AI</dt>
            <dd>OpenAI-compatible Chat Completions with structured outputs and tool calling; mock provider</dd>
            <dt className="text-muted">Research</dt>
            <dd>Cheerio HTML analysis, SSRF-safe fetch, optional Tavily search</dd>
            <dt className="text-muted">Quality</dt>
            <dd>Vitest, ESLint, Recharts for analytics</dd>
          </dl>
        </Row>

        <section className="my-14 rounded-lg border border-line-strong bg-paper px-6 py-8 text-center">
          <h2 className="font-serif text-2xl font-medium">See one lead go through the pipeline</h2>
          <p className="mx-auto mt-2 max-w-lg text-[14px] text-muted">Sign in, pick Example Logistics and watch research, qualification, scoring and outreach run step by step, ending at human approval.</p>
          <Link href="/demo" className={`${buttonVariants({ size: "lg" })} mt-5`}>
            Run the demo
          </Link>
        </section>
      </main>
      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-6xl flex-wrap justify-between gap-2 px-5 py-5 text-[13px] text-muted">
          <span>NovaFlow AI is a fictional company used for this portfolio project.</span>
          <a href="https://github.com/mehranmls4-arch" className="hover:text-ink hover:underline" rel="noopener noreferrer">
            github.com/mehranmls4-arch
          </a>
        </div>
      </footer>
    </div>
  );
}

function Row({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="grid scroll-mt-6 gap-4 border-b border-line py-10 md:grid-cols-[240px_1fr] md:gap-10">
      <h2 className="font-serif text-[22px] font-medium leading-tight">{title}</h2>
      <div className="min-w-0 max-w-[68ch]">{children}</div>
    </section>
  );
}
